config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'groups#index'
  resources :users,only: [:edit,:update]
  resources :groups,only: [:new,:create,:edit,:update] do
    resources :messages,only: [:index,:create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :group_users
  has_many :users , through: :group_users
  has_many :messages
  validates :name,presence: true,uniqueness: true
end

app/models/group_user.rb
class GroupUser < ApplicationRecord
  belongs_to :user
  belongs_to :group
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :group

  validates :content,presence: true, unless: :image?
  mount_uploader :image, ImageUploader
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name,presence: true ,uniqueness: true
  has_many :group_users
  has_many :groups,through: :group_users
  has_many :messages
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController

  def index
    @group = current_user.groups.first
    @messages = @group.messages
  end

  def new
    @group= Group.new
    @group.users << current_user
  end

  def create
    @group = Group.new(group_params)
    if @group.save
      redirect_to root_path ,notice: "グループを作成しました"
    else
      render :new ,alert: "入力に誤りがあります"
    end
  end

  def edit
    @group = Group.find(params[:id])
  end

  def update
    @group = Group.find(params[:id])
    if @group.update(group_params)
      redirect_to root_path,notice: "グループを更新しました"
    else
      render :edit ,alert: "入力に誤りがあります"
    end
  end

  private

  def group_params
    params.require(:group).permit(:name,user_ids: [])
  end

end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_group

  def index
    @messages = @group.messages.includes(:user)
  end

  def create
    message= @group.messages.new(message_params)
    if message.save
      redirect_to group_messages_path(@group),notice: "メッセージを送信しました"
    else
      @messages = @group.messages.includes(:user)
      flash.now[:alert] = 'メッセージを入力してください。'
      render :index
    end
  end

  private

  def message_params
    params.require(:message).permit(:content,:image).merge(user_id: current_user.id)
  end

  def set_group
    @group = Group.find(params[:group_id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def edit

  end

  def update
    if current_user.update(user_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name,:email)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/groups/_form.html.haml
= form_for group do |f|
  - if group.errors.any?
    .chat-group-form__errors
      %h2= "#{group.errors.full_messages.count}件のエラーが発生しました。"
      %ul
        - group.errors.full_messages.each do |message|
          %li= message
  .chat-group-form__field
    .chat-group-form__field--left
      = f.label :name, class: 'chat-group-form__label'
    .chat-group-form__field--right
      = f.text_field :name, class: 'chat__group_name chat-group-form__input', placeholder: 'グループ名を入力してください'
  .chat-group-form__field.clearfix
    / この部分はインクリメンタルサーチ（ユーザー追加の非同期化のときに使用します
  .chat-group-form__field.clearfix
    .chat-group-form__field--left
      %label.chat-group-form__label{:for => "chat_group_チャットメンバー"} チャットメンバー
    .chat-group-form__field--right
      / グループ作成機能の追加時はここにcollection_check_boxesの記述を入れてください
      = f.collection_check_boxes :user_ids, User.all, :id, :name
      / この部分はインクリメンタルサーチ（ユーザー追加の非同期化のときに使用します
  .chat-group-form__field.clearfix
    .chat-group-form__field--left
    .chat-group-form__field--right
      = f.submit class: 'chat-group-form__action-btn'

app/views/groups/edit.html.haml
.chat-group-form
  %h1 チャットグループ編集
  = render partial: 'form', locals: { group: @group }

app/views/groups/index.html.haml
.wrapper
  = render 'messages/side_bar'
  = render 'messages/main_chat'

app/views/groups/new.html.haml
.chat-group-form
  %h1 新規チャットグループ
  = render partial: "form",locals: {group: @group}

app/views/layouts/_notifications.html.haml
.notification
  - flash.each do |key, value|
    = content_tag :div, value, class: key

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title AppName
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = render "layouts/notifications"
    = yield

app/views/messages/_main_chat.html.haml
.main_chat
  .main_chat--top
    .group
      %p.group--name #{@group.name}
      .group--members 
        Member:
        - @group.users.each do |m|
          = m.name
    = link_to("#",class: "edit_btn" ) do
      %p Edit
  .main_chat--middle
    - @messages.each do |m|
      .message
        .message__top
          %p.message__top--name #{m.user.name}
          %p.message__top--date #{m.created_at}
        .message__bottom
          %p.message__bottom--content #{m.content}
  .main_chat--bottom
    = form_with model: [@group,@group.messages.new],class: "message_form" do |f|
      .message_area
        =f.text_field :content,class: "message_text",placeholder: "メッセージを入力して下さい"
        =f.label :image ,class: "file_label" do
          %i.far.fa-image
          =f.file_field :image,class: "file_uploader"
      =f.submit value: "Send",class: "message_submit"

app/views/messages/_side_bar.html.haml
.side_bar
  .side_bar--top
    .user_area
      %p.user_area--name #{current_user.name}
      .user_area--menus
        = link_to new_group_path  do
          %i.fas.fa-edit
        = link_to edit_user_path(current_user)  do
          %i.fas.fa-cog
  .side_bar--bottom
    - current_user.groups.each do |g|
      .message_list
        =link_to "#",class: "group_link" do
          %p.message_list--group_name #{g.name}
          -if g.messages.any?
            %p.message_list--latest_message #{g.messages.last.content}
          - else
            %p.message_list--latest_message メッセージはありません
            

app/views/messages/index.html.haml
.wrapper
  = render partial: 'side_bar'
  = render partial: "main_chat"

app/views/users/edit.html.haml
#account-page.account-page
  .account-page__inner.clearfix
    .account-page__inner--left.account-page__header
      %h2 Edit Account
      %h5 アカウントの編集
      = link_to "ログアウト", destroy_user_session_path,method: :delete, class: 'btn'
      = link_to "トップページに戻る", :back, class: 'btn'
    .account-page__inner--right.user-form
      = form_for(current_user) do |f|
        .field
          .field-label
            = f.label :name
          .field-input
            = f.text_field :name, autofocus: true
        .field
          .field-label
            = f.label :email
          .field-input
            = f.email_field :email
        .actions
          = f.submit "Update", class: 'btn'